# Generated by Django 5.0.1 on 2025-06-25 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_add_gratuito_plan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueioIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        default="Múltiplas tentativas de login falhadas",
                        max_length=200,
                        verbose_name="Motivo do Bloqueio",
                    ),
                ),
                ("bloqueado_ate", models.DateTimeField(verbose_name="Bloqueado Até")),
                (
                    "tentativas_falhadas",
                    models.IntegerField(default=0, verbose_name="Tentativas Falhadas"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Bloqueado",
                "verbose_name_plural": "IPs Bloqueados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ConviteUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_convidado",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Convidado"
                    ),
                ),
                (
                    "nome_convidado",
                    models.CharField(max_length=100, verbose_name="Nome do Convidado"),
                ),
                (
                    "cargo_sugerido",
                    models.CharField(
                        choices=[
                            ("PROPRIETARIO", "Proprietário"),
                            ("GERENTE_GERAL", "Gerente Geral"),
                            ("GERENTE_PRODUCAO", "Gerente de Produção"),
                            ("GERENTE_FINANCEIRO", "Gerente Financeiro"),
                            ("SUPERVISOR", "Supervisor"),
                            ("OPERADOR", "Operador"),
                            ("VENDEDOR", "Vendedor"),
                            ("ASSISTENTE", "Assistente"),
                        ],
                        default="OPERADOR",
                        max_length=20,
                        verbose_name="Cargo Sugerido",
                    ),
                ),
                (
                    "role_empresa",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("GERENTE", "Gerente"),
                            ("OPERADOR", "Operador"),
                            ("VIEWER", "Visualizador"),
                        ],
                        default="OPERADOR",
                        max_length=20,
                        verbose_name="Papel na Empresa",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Token do Convite"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ACEITO", "Aceito"),
                            ("EXPIRADO", "Expirado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField(verbose_name="Expira Em")),
                (
                    "aceito_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aceito Em"
                    ),
                ),
                (
                    "convidado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convites_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convites",
                        to="core.empresa",
                    ),
                ),
                (
                    "usuario_aceito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="convites_aceitos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite de Usuário",
                "verbose_name_plural": "Convites de Usuários",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Endereço IP"),
                ),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "pais",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="País"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "sucesso",
                    models.BooleanField(default=True, verbose_name="Login com Sucesso"),
                ),
                (
                    "motivo_falha",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Motivo da Falha",
                    ),
                ),
                (
                    "data_login",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Login"
                    ),
                ),
                (
                    "data_logout",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Logout"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Login",
                "verbose_name_plural": "Históricos de Login",
                "ordering": ["-data_login"],
            },
        ),
        migrations.CreateModel(
            name="TentativaLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Endereço IP"),
                ),
                (
                    "username_tentativa",
                    models.CharField(
                        max_length=150, verbose_name="Nome de Usuário Tentado"
                    ),
                ),
                (
                    "password_tentativa",
                    models.CharField(
                        max_length=50,
                        verbose_name="Hash da Senha (primeiros caracteres)",
                    ),
                ),
                ("data_tentativa", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentativas_login",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa de Login Falhada",
                "verbose_name_plural": "Tentativas de Login Falhadas",
                "ordering": ["-data_tentativa"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, null=True, verbose_name="Endereço"),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("PROPRIETARIO", "Proprietário"),
                            ("GERENTE_GERAL", "Gerente Geral"),
                            ("GERENTE_PRODUCAO", "Gerente de Produção"),
                            ("GERENTE_FINANCEIRO", "Gerente Financeiro"),
                            ("SUPERVISOR", "Supervisor"),
                            ("OPERADOR", "Operador"),
                            ("VENDEDOR", "Vendedor"),
                            ("ASSISTENTE", "Assistente"),
                        ],
                        default="OPERADOR",
                        max_length=20,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "data_admissao",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Admissão"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "receber_email_notificacoes",
                    models.BooleanField(
                        default=True, verbose_name="Receber Notificações por E-mail"
                    ),
                ),
                (
                    "receber_sms_notificacoes",
                    models.BooleanField(
                        default=False, verbose_name="Receber Notificações por SMS"
                    ),
                ),
                (
                    "aceito_termos",
                    models.BooleanField(
                        default=False, verbose_name="Aceito os Termos de Uso"
                    ),
                ),
                (
                    "data_aceite_termos",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aceite dos Termos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Usuário",
                "verbose_name_plural": "Perfis dos Usuários",
            },
        ),
    ]
