version: '3.8'

services:
  # Aplicação Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: costuraai:dev
    container_name: costuraai_web_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=confeccao_saas.settings.dev
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - costuraai_network
    restart: unless-stopped

  # Redis para cache e Celery
  redis:
    image: redis:7-alpine
    container_name: costuraai_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - costuraai_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Celery Worker (opcional em dev)
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: costuraai:dev
    container_name: costuraai_celery_dev
    command: celery -A confeccao_saas worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=confeccao_saas.settings.dev
    depends_on:
      - redis
    networks:
      - costuraai_network
    restart: unless-stopped

  # Celery Beat (opcional em dev)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: costuraai:dev
    container_name: costuraai_beat_dev
    command: celery -A confeccao_saas beat -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=confeccao_saas.settings.dev
    depends_on:
      - redis
    networks:
      - costuraai_network
    restart: unless-stopped

  # Flower - Monitoramento Celery (opcional)
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: costuraai:dev
    container_name: costuraai_flower_dev
    command: celery -A confeccao_saas flower
    ports:
      - "5555:5555"
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=confeccao_saas.settings.dev
    depends_on:
      - redis
      - celery
    networks:
      - costuraai_network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  costuraai_network:
    driver: bridge 