# Generated by Django 5.0.1 on 2025-06-25 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0003_alter_produto_options_alter_produto_unique_together"),
        ("core", "0003_add_gratuito_plan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacidadeProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "capacidade_diaria",
                    models.IntegerField(
                        default=300,
                        help_text="Quantidade de peças que podem ser produzidas por dia",
                        verbose_name="Capacidade Diária",
                    ),
                ),
                (
                    "capacidade_mensal",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Capacidade Mensal"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidade_producao",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidade de Produção",
                "verbose_name_plural": "Capacidades de Produção",
            },
        ),
        migrations.CreateModel(
            name="OrdemProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "codigo_interno",
                    models.CharField(max_length=20, verbose_name="Código Interno"),
                ),
                ("of", models.CharField(blank=True, max_length=20, verbose_name="OF")),
                (
                    "referencia",
                    models.CharField(max_length=50, verbose_name="Referência"),
                ),
                ("data_entrada", models.DateField(verbose_name="Entrada")),
                ("data_previsao", models.DateField(verbose_name="Previsão")),
                (
                    "data_conclusao",
                    models.DateField(blank=True, null=True, verbose_name="Conclusão"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quant.",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="P. Unit"
                    ),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="P. Total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CADASTRADA", "OP Cadastrada"),
                            ("EM_PRODUCAO", "Em Produção"),
                            ("CONCLUIDA", "Concluída"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="CADASTRADA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
                "ordering": ["-data_entrada", "codigo_interno"],
                "unique_together": {("empresa", "codigo_interno")},
            },
        ),
        migrations.CreateModel(
            name="RelatorioFaturamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mês")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                ("entradas", models.IntegerField(default=0, verbose_name="Entradas")),
                ("saidas", models.IntegerField(default=0, verbose_name="Saídas")),
                (
                    "a_produzir",
                    models.IntegerField(default=0, verbose_name="A Produzir"),
                ),
                (
                    "valor_entradas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_saidas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "falta_receber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data_geracao", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Faturamento",
                "verbose_name_plural": "Relatórios de Faturamento",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("empresa", "mes", "ano")},
            },
        ),
    ]
