# Generated by Django 5.0.1 on 2025-06-25 23:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_alter_produto_options_alter_produto_unique_together"),
        ("core", "0003_add_gratuito_plan_type"),
        ("producao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemproducao",
            name="preco_total",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="custo_material",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Custo Material",
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início Produção"
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="porcentagem_concluida",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="% Concluído"
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="prioridade",
            field=models.IntegerField(
                default=1,
                help_text="1=Baixa, 5=Urgente",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.produto",
                verbose_name="Produto",
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="tipo",
            field=models.CharField(
                choices=[("INTERNA", "Interna"), ("EXTERNA", "Externa")],
                default="INTERNA",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Departamento"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "ordem",
                    models.IntegerField(default=1, verbose_name="Ordem do Processo"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["ordem", "nome"],
                "unique_together": {("empresa", "nome")},
            },
        ),
        migrations.CreateModel(
            name="MateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "unidade_medida",
                    models.CharField(
                        help_text="Ex: metros, kg, unidades",
                        max_length=10,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "estoque_atual",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Estoque Atual",
                    ),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Estoque Mínimo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cadastros.fornecedor",
                        verbose_name="Fornecedor Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria Prima",
                "verbose_name_plural": "Matérias Primas",
                "ordering": ["nome"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="GradeProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                            ("XGG", "XGG"),
                        ],
                        max_length=10,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "quantidade_produzida",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade Produzida",
                    ),
                ),
                (
                    "ordem_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_grade",
                        to="producao.ordemproducao",
                        verbose_name="Ordem de Produção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade de Produção",
                "verbose_name_plural": "Grades de Produção",
                "ordering": ["tamanho"],
                "unique_together": {("ordem_producao", "tamanho")},
            },
        ),
        migrations.CreateModel(
            name="ConsumoMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "quantidade_necessaria",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Quantidade Necessária",
                    ),
                ),
                (
                    "quantidade_utilizada",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Quantidade Utilizada",
                    ),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Custo Unitário"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "ordem_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias_primas",
                        to="producao.ordemproducao",
                        verbose_name="Ordem de Produção",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producao.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producao.materiaprima",
                        verbose_name="Matéria Prima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo de Matéria Prima",
                "verbose_name_plural": "Consumos de Matéria Prima",
                "ordering": ["departamento__ordem", "materia_prima__nome"],
                "unique_together": {
                    ("ordem_producao", "materia_prima", "departamento")
                },
            },
        ),
        migrations.CreateModel(
            name="ProcessoProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Início"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Conclusão"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "porcentagem_concluida",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Concluído",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producao.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "ordem_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="producao.ordemproducao",
                        verbose_name="Ordem de Produção",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo de Produção",
                "verbose_name_plural": "Processos de Produção",
                "ordering": ["departamento__ordem"],
                "unique_together": {("ordem_producao", "departamento")},
            },
        ),
    ]
