# Generated by Django 5.0.1 on 2025-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_gratuito_plan_type"),
        ("producao", "0002_remove_ordemproducao_preco_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemproducao",
            name="numero_op",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Número da OP"
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="op_externa",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="OP Externa"
            ),
        ),
        migrations.AlterModelOptions(
            name="gradeproducao",
            options={
                "ordering": ["id"],
                "verbose_name": "Grade de Produção",
                "verbose_name_plural": "Grades de Produção",
            },
        ),
        migrations.AlterModelOptions(
            name="ordemproducao",
            options={
                "ordering": ["-data_entrada", "numero_op"],
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
            },
        ),
        migrations.AlterUniqueTogether(
            name="ordemproducao",
            unique_together={("empresa", "numero_op")},
        ),
        migrations.AlterField(
            model_name="gradeproducao",
            name="tamanho",
            field=models.CharField(max_length=20, verbose_name="Tamanho"),
        ),
        migrations.AlterField(
            model_name="ordemproducao",
            name="data_entrada",
            field=models.DateField(auto_now_add=True, verbose_name="Data de Entrada"),
        ),
        migrations.AlterField(
            model_name="ordemproducao",
            name="data_previsao",
            field=models.DateField(verbose_name="Previsão de Entrega"),
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="codigo_interno",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="of",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="referencia",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="tipo",
        ),
    ]
