# Generated by Django 5.0.1 on 2025-07-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0004_etapaproducao_linhaproducao_historicoproducao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemproducao",
            name="status",
            field=models.CharField(
                choices=[
                    ("CADASTRADA", "OP Cadastrada"),
                    ("PREPARACAO", "Preparação"),
                    ("FRENTE_EXTERNA", "Frente Externa"),
                    ("MONTAGEM", "Montagem"),
                    ("EM_PRODUCAO", "Em Produção"),
                    ("CONCLUIDA", "Concluída"),
                    ("FINALIZADA", "Finalizada"),
                    ("ENTREGUE", "Entregue"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="CADASTRADA",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
