# Generated by Django 5.0.1 on 2025-07-08 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_alter_produtomateriaprima_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_configuracaobilling_alter_planoassinatura_options_and_more"),
        ("producao", "0005_alter_ordemproducao_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumomateriaprima",
            options={
                "ordering": ["departamento__ordem", "materia_prima__descricao"],
                "verbose_name": "Consumo de Matéria Prima",
                "verbose_name_plural": "Consumos de Matéria Prima",
            },
        ),
        migrations.AlterModelOptions(
            name="materiaprima",
            options={
                "ordering": ["descricao"],
                "verbose_name": "Matéria-Prima",
                "verbose_name_plural": "Matérias-Primas",
            },
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="estoque_atual",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="fornecedor",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="preco_unitario",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="unidade_medida",
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                help_text="Código de barras do produto (opcional).",
                max_length=100,
                null=True,
                verbose_name="Código de Barras",
            ),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="custo_medio_ponderado",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Calculado automaticamente com base nas entradas. Não edite manualmente.",
                max_digits=12,
                verbose_name="Custo Médio Ponderado",
            ),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="fornecedor_preferencial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cadastros.fornecedor",
                verbose_name="Fornecedor Preferencial",
            ),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="materiaprima",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("UN", "Unidade"),
                    ("PC", "Peça"),
                    ("MT", "Metro"),
                    ("M2", "Metro Quadrado"),
                    ("KG", "Quilograma"),
                    ("LT", "Litro"),
                ],
                default="UN",
                max_length=2,
                verbose_name="Unidade de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="codigo",
            field=models.CharField(
                help_text="Código interno da matéria-prima. Pode ser gerado automaticamente ou inserido manualmente.",
                max_length=20,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="descricao",
            field=models.CharField(
                max_length=255, verbose_name="Descrição da Matéria-Prima"
            ),
        ),
        migrations.AlterField(
            model_name="materiaprima",
            name="estoque_minimo",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="O sistema alertará quando o estoque atingir este nível.",
                max_digits=10,
                verbose_name="Estoque Mínimo",
            ),
        ),
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "data_movimento",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
                (
                    "tipo_movimento",
                    models.CharField(
                        choices=[
                            ("ENTRADA_COMPRA", "Entrada por Compra"),
                            ("ENTRADA_AJUSTE", "Entrada por Ajuste"),
                            ("SAIDA_PRODUCAO", "Saída para Produção"),
                            ("SAIDA_AJUSTE", "Saída por Ajuste"),
                            ("SAIDA_PERDA", "Saída por Perda/Dano"),
                            ("INVENTARIO", "Ajuste de Inventário"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimento",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Use valores positivos para entradas e negativos para saídas.",
                        max_digits=10,
                        verbose_name="Quantidade Movimentada",
                    ),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Custo no momento da entrada. Para saídas, é informativo.",
                        max_digits=12,
                        verbose_name="Custo Unitário da Transação",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="producao.materiaprima",
                        verbose_name="Matéria-Prima",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque (Kardex)",
                "ordering": ["-data_movimento", "-pk"],
            },
        ),
    ]
