# Generated by Django 5.0.1 on 2025-07-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_alter_produtomateriaprima_materia_prima"),
        ("estoque", "0001_initial"),
        ("producao", "0006_alter_consumomateriaprima_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="controleetapaop",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="controleetapaop",
            name="etapa",
        ),
        migrations.RemoveField(
            model_name="controleetapaop",
            name="linha_producao",
        ),
        migrations.RemoveField(
            model_name="controleetapaop",
            name="ordem_producao",
        ),
        migrations.RemoveField(
            model_name="controleetapaop",
            name="responsavel",
        ),
        migrations.AlterUniqueTogether(
            name="etapaproducao",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="etapaproducao",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="etapaproducao",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="historicoproducao",
            name="etapa",
        ),
        migrations.RemoveField(
            model_name="historicoproducao",
            name="aprovado_por",
        ),
        migrations.RemoveField(
            model_name="historicoproducao",
            name="linha_producao",
        ),
        migrations.RemoveField(
            model_name="historicoproducao",
            name="operador",
        ),
        migrations.RemoveField(
            model_name="historicoproducao",
            name="ordem_producao",
        ),
        migrations.RemoveField(
            model_name="historicoproducao",
            name="supervisor",
        ),
        migrations.AlterUniqueTogether(
            name="linhaproducao",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="linhaproducao",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="linhaproducao",
            name="operadores",
        ),
        migrations.RemoveField(
            model_name="linhaproducao",
            name="responsavel",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="linha_producao",
        ),
        migrations.AlterUniqueTogether(
            name="materiaprima",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="materiaprima",
            name="fornecedor_preferencial",
        ),
        migrations.AlterField(
            model_name="consumomateriaprima",
            name="materia_prima",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="estoque.materiaprima",
                verbose_name="Matéria Prima",
            ),
        ),
        migrations.RemoveField(
            model_name="movimentacaoestoque",
            name="materia_prima",
        ),
        migrations.RemoveField(
            model_name="movimentacaoestoque",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="movimentacaoestoque",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="movimentacaoestoque",
            name="usuario",
        ),
        migrations.AlterUniqueTogether(
            name="processoproducao",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="processoproducao",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="processoproducao",
            name="ordem_producao",
        ),
        migrations.RemoveField(
            model_name="processoproducao",
            name="responsavel",
        ),
        migrations.AlterUniqueTogether(
            name="relatoriofaturamento",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="relatoriofaturamento",
            name="empresa",
        ),
        migrations.AlterModelOptions(
            name="consumomateriaprima",
            options={
                "ordering": ["materia_prima__descricao"],
                "verbose_name": "Consumo de Matéria Prima",
                "verbose_name_plural": "Consumos de Matéria Prima",
            },
        ),
        migrations.AlterUniqueTogether(
            name="consumomateriaprima",
            unique_together={("ordem_producao", "materia_prima")},
        ),
        migrations.RemoveField(
            model_name="gradeproducao",
            name="quantidade_produzida",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="custo_material",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="data_inicio",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="porcentagem_concluida",
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="quantidade_total",
            field=models.IntegerField(
                default=0,
                help_text="Calculado automaticamente pela grade de produção.",
                verbose_name="Quantidade Total de Peças",
            ),
        ),
        migrations.AlterField(
            model_name="ordemproducao",
            name="status",
            field=models.CharField(
                choices=[
                    ("CADASTRADA", "Cadastrada"),
                    ("EM_PRODUCAO", "Em Produção"),
                    ("CONCLUIDA", "Concluída"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="CADASTRADA",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.DeleteModel(
            name="CapacidadeProducao",
        ),
        migrations.DeleteModel(
            name="ControleEtapaOP",
        ),
        migrations.DeleteModel(
            name="EtapaProducao",
        ),
        migrations.DeleteModel(
            name="HistoricoProducao",
        ),
        migrations.DeleteModel(
            name="LinhaProducao",
        ),
        migrations.DeleteModel(
            name="MateriaPrima",
        ),
        migrations.DeleteModel(
            name="MovimentacaoEstoque",
        ),
        migrations.DeleteModel(
            name="ProcessoProducao",
        ),
        migrations.DeleteModel(
            name="RelatorioFaturamento",
        ),
        migrations.RemoveField(
            model_name="consumomateriaprima",
            name="custo_unitario",
        ),
        migrations.RemoveField(
            model_name="consumomateriaprima",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="consumomateriaprima",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="consumomateriaprima",
            name="quantidade_utilizada",
        ),
    ]
