# Generated by Django 5.0.1 on 2025-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_userprofile_duplicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoassinatura",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("GRATUITO", "Gratuito - R$ 0/mês"),
                    ("BASICO", "Básico - R$ 49/mês"),
                    ("PROFISSIONAL", "Profissional - R$ 99/mês"),
                    ("ENTERPRISE", "Enterprise - R$ 199/mês"),
                ],
                max_length=15,
            ),
        ),
    ]
