# Generated by Django 5.0.1 on 2025-07-03 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_gratuito_plan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_public_key", models.CharField(blank=True, max_length=200)),
                ("stripe_secret_key", models.CharField(blank=True, max_length=200)),
                ("stripe_webhook_secret", models.CharField(blank=True, max_length=200)),
                (
                    "mercadopago_public_key",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "mercadopago_access_token",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "dias_trial_padrao",
                    models.IntegerField(
                        default=30, verbose_name="Dias de Trial Padrão"
                    ),
                ),
                (
                    "dias_tolerancia_pagamento",
                    models.IntegerField(default=5, verbose_name="Dias de Tolerância"),
                ),
                ("enviar_lembrete_pagamento", models.BooleanField(default=True)),
                (
                    "dias_lembrete",
                    models.IntegerField(
                        default=3, verbose_name="Dias Antes do Lembrete"
                    ),
                ),
                (
                    "percentual_imposto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Percentual de Imposto (%)",
                    ),
                ),
                (
                    "email_cobranca",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de Cobrança"
                    ),
                ),
                (
                    "email_suporte",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de Suporte"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de Billing",
                "verbose_name_plural": "Configurações de Billing",
            },
        ),
        migrations.AlterModelOptions(
            name="planoassinatura",
            options={
                "ordering": ["ordem_exibicao", "preco_mensal"],
                "verbose_name": "Plano de Assinatura",
                "verbose_name_plural": "Planos de Assinatura",
            },
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="cor_tema",
            field=models.CharField(
                default="#3b82f6", max_length=7, verbose_name="Cor do Tema (HEX)"
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="desconto_anual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Desconto Anual (%)",
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="descricao_curta",
            field=models.CharField(
                default="", max_length=100, verbose_name="Descrição Curta"
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="destaque",
            field=models.BooleanField(default=False, verbose_name="Plano em Destaque"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="dias_trial",
            field=models.IntegerField(default=30, verbose_name="Dias de Trial"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="max_storage_gb",
            field=models.IntegerField(default=1, verbose_name="Storage (GB)"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="ordem_exibicao",
            field=models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="permite_downgrade",
            field=models.BooleanField(default=True, verbose_name="Permite Downgrade"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="permite_trial",
            field=models.BooleanField(default=True, verbose_name="Permite Trial"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="permite_upgrade",
            field=models.BooleanField(default=True, verbose_name="Permite Upgrade"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="preco_anual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="requer_cartao_trial",
            field=models.BooleanField(
                default=False, verbose_name="Requer Cartão no Trial"
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="tem_backup_automatico",
            field=models.BooleanField(default=False, verbose_name="Backup Automático"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="tem_integracao_contabil",
            field=models.BooleanField(
                default=False, verbose_name="Integração Contábil"
            ),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="tem_multiempresa",
            field=models.BooleanField(default=False, verbose_name="Multi-empresa"),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="planoassinatura",
            name="visivel_site",
            field=models.BooleanField(default=True, verbose_name="Visível no Site"),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="descricao",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="preco_mensal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="tem_api",
            field=models.BooleanField(default=False, verbose_name="Acesso à API"),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="tem_relatorios_avancados",
            field=models.BooleanField(
                default=False, verbose_name="Relatórios Avançados"
            ),
        ),
        migrations.AlterField(
            model_name="planoassinatura",
            name="tem_suporte_prioritario",
            field=models.BooleanField(
                default=False, verbose_name="Suporte Prioritário"
            ),
        ),
        migrations.CreateModel(
            name="CupomDesconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código do Cupom"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "tipo_desconto",
                    models.CharField(
                        choices=[
                            ("PERCENTUAL", "Percentual"),
                            ("VALOR_FIXO", "Valor Fixo"),
                            ("PRIMEIRO_MES_GRATIS", "Primeiro Mês Grátis"),
                        ],
                        default="PERCENTUAL",
                        max_length=20,
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor/Percentual do Desconto",
                    ),
                ),
                ("data_inicio", models.DateTimeField(verbose_name="Data de Início")),
                ("data_fim", models.DateTimeField(verbose_name="Data de Fim")),
                (
                    "limite_uso",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Limite de Uso"
                    ),
                ),
                (
                    "vezes_usado",
                    models.IntegerField(default=0, verbose_name="Vezes Usado"),
                ),
                ("apenas_novos_clientes", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "planos_aplicaveis",
                    models.ManyToManyField(
                        blank=True,
                        to="core.planoassinatura",
                        verbose_name="Planos Aplicáveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cupom de Desconto",
                "verbose_name_plural": "Cupons de Desconto",
            },
        ),
        migrations.CreateModel(
            name="HistoricoAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIACAO", "Criação"),
                            ("UPGRADE", "Upgrade"),
                            ("DOWNGRADE", "Downgrade"),
                            ("REATIVACAO", "Reativação"),
                            ("SUSPENSAO", "Suspensão"),
                            ("CANCELAMENTO", "Cancelamento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("valor_novo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_proporcional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "motivo",
                    models.TextField(blank=True, verbose_name="Motivo da Mudança"),
                ),
                ("data_mudanca", models.DateTimeField(auto_now_add=True)),
                (
                    "data_vigencia",
                    models.DateTimeField(verbose_name="Data de Vigência"),
                ),
                (
                    "assinatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="core.assinaturaempresa",
                    ),
                ),
                (
                    "plano_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_anterior",
                        to="core.planoassinatura",
                    ),
                ),
                (
                    "plano_novo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_novo",
                        to="core.planoassinatura",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Assinatura",
                "verbose_name_plural": "Históricos de Assinatura",
                "ordering": ["-data_mudanca"],
            },
        ),
        migrations.CreateModel(
            name="TransacaoPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_transacao",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID da Transação"
                    ),
                ),
                (
                    "id_gateway",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID no Gateway"
                    ),
                ),
                (
                    "tipo_transacao",
                    models.CharField(
                        choices=[
                            ("ASSINATURA", "Assinatura Mensal"),
                            ("UPGRADE", "Upgrade de Plano"),
                            ("DOWNGRADE", "Downgrade de Plano"),
                            ("REATIVACAO", "Reativação"),
                            ("CANCELAMENTO", "Cancelamento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("MERCADOPAGO", "Mercado Pago"),
                            ("PAGSEGURO", "PagSeguro"),
                            ("PAYPAL", "PayPal"),
                            ("PIX", "PIX"),
                            ("BOLETO", "Boleto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                            ("CANCELADA", "Cancelada"),
                            ("ESTORNADA", "Estornada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Desconto",
                    ),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Final"
                    ),
                ),
                (
                    "metodo_pagamento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Método de Pagamento"
                    ),
                ),
                (
                    "ultimos_4_digitos",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Últimos 4 Dígitos"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_processamento", models.DateTimeField(blank=True, null=True)),
                ("data_aprovacao", models.DateTimeField(blank=True, null=True)),
                ("data_vencimento", models.DateTimeField(blank=True, null=True)),
                (
                    "dados_gateway",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados do Gateway"
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "assinatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes",
                        to="core.assinaturaempresa",
                    ),
                ),
                (
                    "cupom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cupomdesconto",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.planoassinatura",
                        verbose_name="Plano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação de Pagamento",
                "verbose_name_plural": "Transações de Pagamento",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "status"],
                        name="core_transa_empresa_82f22f_idx",
                    ),
                    models.Index(
                        fields=["id_gateway"], name="core_transa_id_gate_f46e04_idx"
                    ),
                    models.Index(
                        fields=["data_criacao"], name="core_transa_data_cr_dfc349_idx"
                    ),
                ],
            },
        ),
    ]
