# Generated by Django 5.0.1 on 2025-06-28 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0003_alter_produto_options_alter_produto_unique_together"),
        ("core", "0003_add_gratuito_plan_type"),
        ("producao", "0003_alter_gradeproducao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "numero_conta",
                    models.CharField(max_length=20, verbose_name="Número da Conta"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Total"
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Recebido",
                    ),
                ),
                ("data_emissao", models.DateField(verbose_name="Data de Emissão")),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PARCIAL", "Parcial"),
                            ("PAGO", "Pago"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "ordem_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_receber",
                        to="producao.ordemproducao",
                        verbose_name="Ordem de Produção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Receber",
                "verbose_name_plural": "Contas a Receber",
                "ordering": ["-data_emissao", "data_vencimento"],
                "unique_together": {("empresa", "numero_conta")},
            },
        ),
        migrations.CreateModel(
            name="PagamentoRecebido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Pago"
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="Data do Pagamento")),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "PIX"),
                            ("TRANSFERENCIA", "Transferência"),
                            ("CARTAO_CREDITO", "Cartão de Crédito"),
                            ("CARTAO_DEBITO", "Cartão de Débito"),
                            ("BOLETO", "Boleto"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=10, verbose_name="Agência"),
                ),
                (
                    "conta",
                    models.CharField(blank=True, max_length=20, verbose_name="Conta"),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número do Documento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "conta_receber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="financeiro.contareceber",
                        verbose_name="Conta a Receber",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento Recebido",
                "verbose_name_plural": "Pagamentos Recebidos",
                "ordering": ["-data_pagamento"],
            },
        ),
        migrations.CreateModel(
            name="FaturamentoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("mes", models.IntegerField(verbose_name="Mês")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                (
                    "entradas",
                    models.IntegerField(
                        default=0, verbose_name="Entradas (OPs Cadastradas)"
                    ),
                ),
                (
                    "saidas",
                    models.IntegerField(
                        default=0, verbose_name="Saídas (OPs Concluídas)"
                    ),
                ),
                (
                    "a_produzir",
                    models.IntegerField(
                        default=0, verbose_name="A Produzir (OPs em Andamento)"
                    ),
                ),
                (
                    "valor_entradas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor das Entradas",
                    ),
                ),
                (
                    "valor_saidas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor das Saídas",
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Recebido",
                    ),
                ),
                (
                    "falta_receber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Falta Receber",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faturamento Mensal",
                "verbose_name_plural": "Faturamentos Mensais",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("empresa", "mes", "ano")},
            },
        ),
    ]
