# Generated by Django 5.0.1 on 2025-06-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
        ("producao", "0003_alter_gradeproducao_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contareceber",
            name="ordem_producao",
            field=models.ForeignKey(
                blank=True,
                help_text="Deixe em branco para contas independentes",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contas_receber",
                to="producao.ordemproducao",
                verbose_name="Ordem de Produção",
            ),
        ),
    ]
