# Generated by Django 5.0.1 on 2025-06-24 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_uteis_mes",
                    models.IntegerField(default=22, verbose_name="Dias Úteis por Mês"),
                ),
                (
                    "horas_trabalho_dia",
                    models.IntegerField(
                        default=8, verbose_name="Horas de Trabalho por Dia"
                    ),
                ),
                (
                    "moeda_padrao",
                    models.CharField(
                        default="BRL", max_length=3, verbose_name="Moeda Padrão"
                    ),
                ),
                (
                    "forma_pagamento_padrao",
                    models.CharField(
                        default="À Vista",
                        max_length=50,
                        verbose_name="Forma de Pagamento Padrão",
                    ),
                ),
                (
                    "notificar_prazo_op",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Prazo de OP"
                    ),
                ),
                (
                    "dias_antecedencia_prazo",
                    models.IntegerField(
                        default=3, verbose_name="Dias de Antecedência para Prazo"
                    ),
                ),
                (
                    "horario_envio_relatorio",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Horário de Envio de Relatório Diário",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração da Empresa",
                "verbose_name_plural": "Configurações das Empresas",
            },
        ),
        migrations.CreateModel(
            name="EmpresaStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_ops_mes",
                    models.IntegerField(default=0, verbose_name="Total de OPs no Mês"),
                ),
                (
                    "faturamento_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Faturamento do Mês",
                    ),
                ),
                (
                    "ops_atrasadas",
                    models.IntegerField(default=0, verbose_name="OPs Atrasadas"),
                ),
                (
                    "capacidade_utilizada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Capacidade Utilizada (%)",
                    ),
                ),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status da Empresa",
                "verbose_name_plural": "Status das Empresas",
            },
        ),
    ]
