# Generated by Django 5.0.1 on 2025-06-25 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_add_gratuito_plan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, verbose_name="Nome da Categoria"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Produto",
                "verbose_name_plural": "Categorias de Produtos",
                "ordering": ["nome"],
                "unique_together": {("empresa", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome/Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Inscrição Estadual"
                    ),
                ),
                ("endereco", models.TextField(verbose_name="Endereço")),
                ("bairro", models.CharField(max_length=50, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                ("cep", models.CharField(max_length=10, verbose_name="CEP")),
                (
                    "contato_principal",
                    models.CharField(max_length=100, verbose_name="Contato Principal"),
                ),
                (
                    "telefone_comercial",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Comercial"
                    ),
                ),
                (
                    "telefone_celular",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
                "unique_together": {("empresa", "cnpj")},
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=150, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "tipo_fornecedor",
                    models.CharField(
                        choices=[
                            ("FACCAO", "Facção"),
                            ("MATERIA_PRIMA", "Matéria Prima"),
                            ("AVIAMENTOS", "Aviamentos"),
                            ("SERVICOS", "Serviços"),
                            ("OUTROS", "Outros"),
                        ],
                        default="FACCAO",
                        max_length=15,
                        verbose_name="Tipo de Fornecedor",
                    ),
                ),
                ("cnpj_cpf", models.CharField(max_length=18, verbose_name="CNPJ/CPF")),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Inscrição Estadual"
                    ),
                ),
                ("endereco", models.TextField(verbose_name="Endereço")),
                ("bairro", models.CharField(max_length=50, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
                ("uf", models.CharField(max_length=2, verbose_name="UF")),
                ("cep", models.CharField(max_length=10, verbose_name="CEP")),
                (
                    "contato_principal",
                    models.CharField(max_length=100, verbose_name="Contato Principal"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=10, verbose_name="Agência"),
                ),
                (
                    "conta",
                    models.CharField(blank=True, max_length=20, verbose_name="Conta"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["razao_social"],
                "unique_together": {("empresa", "cnpj_cpf")},
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "referencia",
                    models.CharField(max_length=50, verbose_name="Referência"),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Produto"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "cor",
                    models.CharField(blank=True, max_length=30, verbose_name="Cor"),
                ),
                (
                    "tamanho",
                    models.CharField(blank=True, max_length=10, verbose_name="Tamanho"),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Material"
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo Unitário",
                    ),
                ),
                (
                    "tempo_producao_horas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Tempo de Produção (horas)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="produtos/",
                        verbose_name="Foto do Produto",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.categoriaproduto",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["categoria", "nome"],
                "unique_together": {("empresa", "referencia")},
            },
        ),
    ]
