# Generated by Django 5.0.1 on 2025-06-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["referencia"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="produto",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo",
            field=models.CharField(
                default="TEMP", max_length=20, verbose_name="Código"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_cor",
            field=models.CharField(
                default="00000", max_length=10, verbose_name="Código da Cor"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="consumo_fio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Consumo Fio (metros)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="consumo_linha_externa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Consumo Linha Externa (metros)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="consumo_linha_interna",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Consumo Linha Interna (metros)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produtos/",
                verbose_name="Imagem do Produto",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="produto",
            name="produto",
            field=models.CharField(
                choices=[
                    ("CALCA", "Calça"),
                    ("SHORTS", "Shorts"),
                    ("SAIA", "Saia"),
                    ("VESTIDO", "Vestido"),
                    ("BLUSA", "Blusa"),
                    ("CAMISA", "Camisa"),
                    ("JAQUETA", "Jaqueta"),
                    ("OUTROS", "Outros"),
                ],
                default="OUTROS",
                max_length=10,
                verbose_name="Tipo de Produto",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("PC", "Peça"),
                    ("KG", "Quilograma"),
                    ("MT", "Metro"),
                    ("UN", "Unidade"),
                ],
                default="PC",
                max_length=2,
                verbose_name="Unidade",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="cor",
            field=models.CharField(
                default="Sem cor definida", max_length=50, verbose_name="Nome da Cor"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(
                default="Produto sem descrição", verbose_name="Descrição do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço Unitário",
            ),
        ),
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="material",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tempo_producao_horas",
        ),
    ]
