# Generated by Django 5.0.1 on 2025-06-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastros",
            "0002_alter_produto_options_alter_produto_unique_together_and_more",
        ),
        ("core", "0003_add_gratuito_plan_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["codigo", "referencia"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="produto",
            unique_together={("empresa", "codigo")},
        ),
    ]
