# Generated by Django 5.0.1 on 2025-07-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_alter_produto_options_alter_produto_unique_together"),
        ("core", "0004_configuracaobilling_alter_planoassinatura_options_and_more"),
        ("producao", "0003_alter_gradeproducao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custo para produzir o produto",
                max_digits=10,
                null=True,
                verbose_name="Preço de Custo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_venda",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço de venda do produto",
                max_digits=10,
                null=True,
                verbose_name="Preço de Venda",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="custo_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Custo Unitário (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço Unitário (Legado)",
            ),
        ),
        migrations.CreateModel(
            name="ProdutoMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantidade da matéria-prima necessária para produzir 1 unidade do produto",
                        max_digits=10,
                        verbose_name="Quantidade Necessária",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producao.materiaprima",
                        verbose_name="Matéria-Prima",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias_primas",
                        to="cadastros.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria-Prima do Produto",
                "verbose_name_plural": "Matérias-Primas do Produto",
                "ordering": ["materia_prima__nome"],
                "unique_together": {("produto", "materia_prima")},
            },
        ),
    ]
