# Generated by Django 5.0.1 on 2025-07-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_produto_preco_custo_produto_preco_venda_and_more"),
        ("core", "0004_configuracaobilling_alter_planoassinatura_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TamanhoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ADULTO", "Adulto (P, M, G, etc.)"),
                            ("NUMERICO", "Numérico (36, 38, 40, etc.)"),
                            ("INFANTIL", "Infantil por idade (4, 6, 8, etc.)"),
                            ("PERSONALIZADO", "Personalizado"),
                        ],
                        default="ADULTO",
                        max_length=15,
                        verbose_name="Tipo de Tamanho",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ex: P, M, G, 36, 38, 4, 6, etc.",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Ex: Pequeno, Médio, Grande, 36 anos, etc.",
                        max_length=50,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=1,
                        help_text="Ordem de exibição (menor = primeiro)",
                        verbose_name="Ordem",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho de Produto",
                "verbose_name_plural": "Tamanhos de Produtos",
                "ordering": ["tipo", "ordem", "codigo"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="ProdutoTamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "preco_custo_especifico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Se preenchido, sobrescreve o preço padrão do produto para este tamanho",
                        max_digits=10,
                        null=True,
                        verbose_name="Preço de Custo Específico",
                    ),
                ),
                (
                    "preco_venda_especifico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Se preenchido, sobrescreve o preço padrão do produto para este tamanho",
                        max_digits=10,
                        null=True,
                        verbose_name="Preço de Venda Específico",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Disponível")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.tamanhoproduto",
                        verbose_name="Tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto por Tamanho",
                "verbose_name_plural": "Produtos por Tamanho",
                "ordering": ["tamanho__ordem"],
                "unique_together": {("produto", "tamanho")},
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="tamanhos",
            field=models.ManyToManyField(
                help_text="Tamanhos em que este produto está disponível",
                through="cadastros.ProdutoTamanho",
                to="cadastros.tamanhoproduto",
                verbose_name="Tamanhos Disponíveis",
            ),
        ),
    ]
