# Generated by Django 5.0.1 on 2025-07-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_tamanhoproduto_produtotamanho_produto_tamanhos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produtomateriaprima",
            options={
                "ordering": ["materia_prima__descricao"],
                "verbose_name": "Matéria-Prima do Produto",
                "verbose_name_plural": "Matérias-Primas do Produto",
            },
        ),
        migrations.AlterField(
            model_name="produto",
            name="consumo_fio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Consumo Fio (Kg)",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="consumo_linha_externa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Consumo Linha Externa (Metros)",
            ),
        ),
    ]
