# Generated by Django 5.0.1 on 2025-07-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_alter_produtomateriaprima_options_and_more"),
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtomateriaprima",
            name="materia_prima",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="estoque.materiaprima",
                verbose_name="Matéria-Prima",
            ),
        ),
    ]
