# Generated by Django 5.0.1 on 2025-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_alter_produtomateriaprima_materia_prima"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="custo_total_materias_primas",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Calculado automaticamente pela ficha técnica do produto.",
                max_digits=10,
                verbose_name="Custo Total de Matérias-Primas",
            ),
        ),
    ]
